spring.application.name=spring
server.port=8081

#spring.datasource.url=jdbc:postgresql://localhost:5432/fsadb
#spring.datasource.username=admin
#spring.datasource.password=Admin@123
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:mysql://localhost:3306/fsadb
spring.datasource.username=root
#set environment variable with alias
spring.datasource.password=${PW:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
app.jwt.expiration-ms=480000000000
app.jwt.secret=dhfjkahsdjhkjdfhksfksfhklfjklfjksl@111
spring.jpa.properties.hibernate.format_sql=true